### ISSUE TITLE
WriteDummyDBF in WriteGeometryCollection Method

### ISSUE THREAD

**Issue by petlof** [NetTopologySuite/GeoAPI#11]
Having some problems with my DBF-file is getting it's header overwritten when writing the collection of shapes to disk. 
Found that it's actually a line in the WriteGeometryCollection-method that overwrites my DBF-file that I already have created.

I don't like this design since it's not clear for the one using NTS that the DBF-file needs to be written after the shape-file.
Shouldn't we add a check here and not create the DummyDbf (if it should be there at all) if the DBF-header of DbfWriter already have been written. Of if the DBF-file already exists.

https://github.com/NetTopologySuite/NetTopologySuite/blob/master/NetTopologySuite.IO/NetTopologySuite.IO.GeoTools/ShapefileWriter.cs#L188

https://github.com/NetTopologySuite/NetTopologySuite/blob/master/NetTopologySuite.IO/NetTopologySuite.IO.GeoTools/ShapefileWriter.cs#L204

**Comment by petlof** [comment]
Maybe @FObermaier have some more comments about this

**Comment by jaundice** [comment]
I don't really like the dummy dbf writing, but it predates my changes and I didn't have time to restructure it.

**Comment by petlof** [comment]
Moving the discussion to correct repo:
https://github.com/NetTopologySuite/NetTopologySuite/issues/56
