### ISSUE TITLE
Support for the M ordinates

### ISSUE THREAD

**Issue by netgrim** [NetTopologySuite/GeoAPI#12]
Is the support for the M ordinates is planned or I don't understand how it works

The coordinate.cs is the central class for a coordinate but what about having custom class like:

CoordinateXY
CoordinateXYZ
CoordinateXYM
CoordinateXYZM

**Comment by DGuidi** [comment]
see [BasicCoordinateSequenceTest](https://github.com/NetTopologySuite/NetTopologySuite/blob/4881c1917a80a608eae057995f93e0742efc1310/NetTopologySuite.Tests.NUnit/Geometries/Implementation/BasicCoordinateSequenceTest.cs)

**Comment by FObermaier** [comment]
@DGuidi: Coordinate does not have any M ordinates.
@netgrim:Support for M ordinates is provided via coordinate sequences (ICoordinateSequence). There are several implementations that can handle M ordinate values. The default (CoordinateArraySequence) does not.

**Comment by DGuidi** [comment]
> Coordinate does not have any M ordinates.

yep, fixed my comment to (try to) be more clear.
