### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by xivk** [NetTopologySuite/GeoAPI#13]
I added a new .NET core project:

https://github.com/NetTopologySuite/GeoAPI/tree/refactoring/netstandard

I added all the source files to this new project and made links to the source files in the regular .NET and PCL project.

What do you guys think? Is this ok to merge? Can someone update the build process and include this in the packages?

**Comment by DGuidi** [comment]
+1 for integration. for build and nuget, maybe we can take a look also if/when NTS is .NET Core compliant.

**Comment by DGuidi** [comment]
there are some problems with travis build. see #14
