### ISSUE TITLE
Move code from GeoApi.Core project to GeoApi

### ISSUE THREAD

**Issue by DGuidi** [NetTopologySuite/GeoAPI#15]
Other projects should use linked files

**Comment by xivk** [comment]
I would have done it that way to begin with but the core project doesn't allow linked files.... this was the only option AFAIK

**Comment by DGuidi** [comment]
ah, ok. we'll stick with this. no problem at all, I suppose.

**Comment by xivk** [comment]
@DGuidi There is an alternative for this and that's migrating *everything* to the new project.json/xproj setup. This can be used to target different platforms in the same project. It would mean a lot cleaner code/project.

The disadvantage of this approach is that support in VS is not default, you need to install 'update 3' and .NET core tooling.

But I do think this is the best approach for GeoAPI in let's say 6 months. Also NTS...

Check OsmSharp where I did this already in the develop branch: https://github.com/OsmSharp/core

**Comment by DGuidi** [comment]
@xivk I think it's ok to create separate PCL+NET-Core+NET-Standard projects for ProjNET and NTS too.
But, honestly, this isn't a task I can effort now. Any contribution from you, or another volunteer, like the one with GeoAPI is well accepted.
-1 to remove PCL and NET-Standard projects.

**Comment by xivk** [comment]
Not asking anyone to do the work and definetly not doing this right now just thinking about the future of these projects. I'll probably take on the work of porting NTS next...

My business directly depends on GeoAPI and NTS and I want to make sure I can keep depending on them. Something I would like to see is a way to create pre-release packages? I'll create a seperate issue to discuss this.

**Comment by DGuidi** [comment]
I've created distinct issues in NTS and ProjNET, just to track this kind of work
