### ISSUE TITLE
Envelope.Parse doesn't use NumberFormatInfo.InvariantInfo by default

### ISSUE THREAD

**Issue by FObermaier** [NetTopologySuite/GeoAPI#24]
On e.g. machine with german locale `Envelope.Parse("Env[10.1 : 10.1, 10.1 : 10.1]");` results in `"Env[101 : 101, 101 : 101]"`

@DGuidi We should move/copy `Envelope` and `Coordinate` test to this project.

**Comment by DGuidi** [comment]
+1 for move: probably parse need to be done using InvariantCulture

**Comment by DGuidi** [comment]
made a fix, but you're right: test code for classes in GeoAPI projects should be moved hered

**Comment by FObermaier** [comment]
Added
