### ISSUE TITLE
Changes to the packages publishing and branching

### ISSUE THREAD

**Issue by xivk** [NetTopologySuite/GeoAPI#28]
Similar to https://github.com/NetTopologySuite/NetTopologySuite/issues/179 but do those things here.

Already done:

- Added develop branch.
- Setup build (needs work).

TODO:

- [x] Change develop to the default branch.
- [x] Update README.

**Comment by xivk** [comment]
**So here we now also have automatic package publishing on develop.** The same issue exists as with NTS:


- [ ] Hiding packages pre1-pre9 (the packages are still there, just not visible, searchable anymore but restoring them still works. Just saying this won't break anyones projects)
    **I don't have access to do this, who does? @DGuidi @FObermaier **
- [x] Republish starting from 006, already active.

**Comment by DGuidi** [comment]
I don't see pre006 package, hidden all 1.7.5 except 1.7.5-pre4

**Comment by airbreather** [comment]
@xivk I sat down to go update the NTS side for 717719d, but it looks like the auto-builds for GeoAPI haven't been working.  The latest is `-pre4`.

**Comment by airbreather** [comment]
I've made a `-pre006` manually, published it, and hid `-pre4`.

**Comment by xivk** [comment]
The automatic builds are working now, you can send me an email if you want access to the build server...
