### ISSUE TITLE
GeoAPI.CoordinateSystems nuget package

### ISSUE THREAD

**Issue by FObermaier** [NetTopologySuite/GeoAPI#37]
I split up the `GeoAPI` package into `GeoAPI` and `GeoAPI.CoordinateSystems`.

We need to 
- [x] rename `GeoAPI` to `GeoAPI.Core` package,
- [x] add `GeoAPI.CoordinateSystems` package and
- [x] add `GeoAPI` meta package

As @xivk  maintains the build server pushing the packages, could you please help doing that?

**Comment by xivk** [comment]
Ok, no problem :+1:

I think just updating the nuspecs should be fine, i'll include GeoAPI.CoordinateSystems in the build.

Not sure on how to create a metapackage.

**Comment by xivk** [comment]
Why the rename btw?

**Comment by xivk** [comment]
GeoAPI.CoordinateSystems is now included in the build, should appear next time, the rename has to be done in the GeoAPI.nuspec file.

**Comment by xivk** [comment]
Ah ok, that makes sense... if you can point me to whatever needs to be done for the meta-package then we're finished.

**Comment by FObermaier** [comment]
I can see the packages now. Unfortunately they are not in sync.
They need to be build in this order:
1. `GeoAPI.Core`
2. `GeoAPI.CoordinateSystems` (relies on `GeoAPI.Core`)
3. `GeoAPI` (relies on `GeoAPI.CoordinateSystem` and thus on `GeoAPI.Core`)

**Comment by xivk** [comment]
What do you mean in sync? 

There is also an error now in one of the nuspec's:

`[pack] <dependencies> element must not contain both <group> and <dependency> child elements.`

If you make a useraccount on the [server](https://build.itinero.tech/) I can give you access to manage this.

**Comment by FObermaier** [comment]
Seems to be resolved. Waiting for indexing to complete.

**Comment by FObermaier** [comment]
@xivk, sorry to bother you but could you add publishing `GeoAPI.Core` to the nuget feed.
I fixed the other issues with the packages and could then push for version 1.75-pre018.
Btw, I registered at your build server.

**Comment by xivk** [comment]
It's now building and pushing these three packages:

- GeoAPI.nuspec
- GeoAPI.CoordinateSystems.nuspec
- GeoAPI.Core.nuspec

I gave you admin access to all the NTS related projects (but not 100% sure if I configured it correctly).

**Comment by FObermaier** [comment]
@xivk, thanks for the support on this one!
