### ISSUE TITLE
Get permissions from all contributors (at least all who have made significant changes) to agree to license change.

### ISSUE THREAD

**Issue by airbreather** [NetTopologySuite/GeoAPI#43]
This is the GeoAPI version of NetTopologySuite/NetTopologySuite#238.  I'm assuming that people who have already given their consent on that issue are likely to give consent on this one, so I'm not going to immediately go through the effort of linking their individual commits.

Authors who seem to have made significant contributions (these are the only ones whom I will mention with @ where a GitHub name is available):
- [x] Felix Obermaier / @FObermaier
- [x] Diego Guidi / @DGuidi
- [x] Ben Abelshausen / @xivk
- [x] Joe Amenta / @airbreather
- [x] Yoh Deadfall / @YohDeadfall
- [x] Fabrício Godoy / @skarllot (~~c59d973~~, 9311a86, ~~9a4eae3~~, 6fcb7a2, 6583525)

Authors whose contributions to code still in `develop` strictly seem small enough not to be worth fretting over (this is based on judgment calls, so not crossing out the authors yet):
- [ ] Peet Whittaker / @\peetw (~~c8f2452~~)

**Comment by YohDeadfall** [comment]
Agree.

**Comment by xivk** [comment]
Agreed.

**Comment by skarllot** [comment]
Agreed

**Comment by FObermaier** [comment]
I declare this query closed
