### ISSUE TITLE
List of points -> polygon

### ISSUE THREAD

**Issue by Lotto2** [NetTopologySuite/GeoAPI#5]
does GeoAPI provide some sort of function to create a polygon that contains all points in a list? goal is the smallest polygon that contains all points. something like ST_MakePolygon or ST_ConvexHull known from PostgreSQL.

if there is no single function, is there a way to get to the polygon in steps?

thankful for help...

**Comment by DGuidi** [comment]
take a look at NTS: http://goo.gl/j0UcVY

**Comment by Lotto2** [comment]
Saluti DGuidi,

thanx for the hint, i applied this ConvexHull. result is this:

![noconvexhull](https://cloud.githubusercontent.com/assets/10242264/6003832/f038f768-aafe-11e4-94d4-be146a5f00ad.png)

indeed it is a polygon around the green points, but it is not the smallest possible polygon.

any further suggestions?

**Comment by DGuidi** [comment]
[here](https://groups.google.com/forum/#!forum/nettopologysuite) for help
