### ISSUE TITLE
Is the GeoAPI 1.7.5 Nuget package missing dll's?

### ISSUE THREAD

**Issue by JeffSchwandt** [NetTopologySuite/GeoAPI#51]
When I update my solution to GeoAPI 1.7.5, my build breaks with dozens of missing references to GeoAPI.Geometries.
When I check the packages\GeoAPI.1.7.5 folder, all that is there is GeoAPI.1.7.5.nupkg.
Shouldn't there be a lib folder?

**Comment by airbreather** [comment]
1.7.5 has split the GeoAPI package into two, the GeoAPI package has dependencies on the two new ones.

Try doing NuGet package restore again?
