### ISSUE TITLE
Remove obsolete interfaces, classes and members

### ISSUE THREAD

**Issue by FObermaier** [NetTopologySuite/GeoAPI#54]
The following interfaces, classes, enums or some of their members have been marked obsolete (for a long time)   

Item | Reason
---- | ------
`ICoordinate` | Its use was a big performance hit.
`IEnvelope` | dito
`GeoAPI.Operation.Buffer.BufferStyle` | has been superceeded by `GeoAPI.Operation.Buffer.IBufferParameters`
`ICoordinateSequence.Reversed()` | not convorm with JTS
usage of `System.ICloneable` | deprecated in JTS v1.15
`Envelope.Overlaps` | usage of `Envelope.Intersects` preferred
`IGeometryFactory.CreateMultiPoint(Coordinate[]);` | deprecated in JTS v1.15, use new `CreateMultiPointFromCoords` method
`IGeometry.Equals` | usage of either `IGeometry.EqualsExcact` or `IGeometry.EqualsTopologically` preferred
`IMultiLineString.Reversed()` | `IGeometry.Reversed()`

As we are having breaking changes for the v2.0 it might be the time to remove tem altogether.
Please use 👍 or 👎 on this post, comments are welcome, too.

**Comment by airbreather** [comment]
`IEnvelope` and `BufferStyle` have been `Obsolete` for a while, too.

Members of some other types have been `Obsolete` for a long time, too, such as `Envelope.Overlaps`.
