### ISSUE TITLE
Future of Coordinate class

### ISSUE THREAD

**Issue by FObermaier** [NetTopologySuite/GeoAPI#55]
The former `Coordinate` class has been disected into four hierarchical classes:
* `CoordinateXY`
  * `CoordinateXYM`
  * `CoordinateXYZ`
    * `CoordinateXYZM`

Where applicable, the defined interfaces have been refactored to use `CoordinateXY` as coordinate class. 
`Coordinate` class has received some conversion operators (implicit vice versa to `CoordinateXY` and explicit to `CoordinateXYZ`)

We have two choices: 
* Mark `Coordinate` obsolete and let it stay around with `CoordinateXY` et. al. (👍 )
  * Might help transforming dependant projects
  * _to be continued_
* Remove `Coordinate`, strip "XY" off of `CoordinateXY` et. at. (👎 )
  * Cleaner, less changes in NTS
  * _to be continued_

**Comment by DGuidi** [comment]
my two cents: 
CoordinateXY => Coordinate
CoordinateXYM => CoordinateM
CoordinateXYZ => CoordinateZ
CoordinateXYZM => CoordinateZM
