### ISSUE TITLE
CoordinateXY.CompareTo(object) is incorrect

### ISSUE THREAD

**Issue by airbreather** [NetTopologySuite/GeoAPI#58]
`CompareTo(object)` is incorrect; we're supposed to throw `ArgumentException` if the instances are of incompatible types.  Otherwise, there's no way to guarantee that `a.CompareTo(b)` and `b.CompareTo(a)` are always consistent with one another (which is a requirement for many sorting algorithms... see also NetTopologySuite/NetTopologySuite#260)

Copied from https://github.com/NetTopologySuite/GeoAPI/pull/56#discussion_r230598951

**Comment by FObermaier** [comment]
Agreed.

For `CompareTo(object)` I propose to check for 
* `null` => `ArgumentNullException`
* invalid type => `ArgumentException`

For `CompareTo(CoordinateXY)` we just check for 
* `null` => `ArgumentNullException`

**Comment by FObermaier** [comment]
Removing all checks and is-casts from the `CompareTo` method(s) would cause `NullReferenceException` to be thrown. This would be more like it is done in JTS, but I don't know if it is better.

**Comment by airbreather** [comment]
> For `CompareTo(object)` I propose to check for 
> * `null` => `ArgumentNullException`
> * invalid type => `ArgumentException`
>
> For `CompareTo(CoordinateXY)` we just check for 
> * `null` => `ArgumentNullException`

This is, as I understand it, the idiomatic way to do it, so I agree.

> Removing all checks and is-casts from the `CompareTo` method(s) would cause `NullReferenceException` to be thrown. This would be more like it is done in JTS, but I don't know if it is better.

I don't think that's better.  I strongly agree with throwing `ArgumentNullException` in cases where a `NullReferenceException` would be thrown otherwise.
