### ISSUE TITLE
Remove redundant interface members

### ISSUE THREAD

**Issue by airbreather** [NetTopologySuite/GeoAPI#67]
Every member defined on an interface represents an added cost to whoever is ultimately going to implement it.  Some of our interfaces have gotten *way* out of hand, and #30* seeks to help with that by  segregating the interfaces more so that the implementer doesn't have to account for **everything** under the sun.
- *looking at **just** the original issue, not what the comments turned it into

However, we could get some "quick wins" towards usability by removing some members that are outright redundant with other members already on the same interface (adding extension methods in their place where appropriate to avoid harming usability).

I propose that we try to simplify as much of this list as we reasonably can...

## `ICoordinateBuffer`
`AddCoordinate(...)` is redundant with `InsertCoordinate(Count, ...)`, but can we just get rid of this interface?

## `ICoordinateSequence`
`Ordinate` / `Ordinates` and friends... that's a whole other topic of its own.

`GetCoordinateCopy(i)` is equivalent to `GetCoordinate(i, CreateCoordinate())`.

`ToCoordinateArray()` is a bunch of `GetCoordinateCopy(i)` calls to initialize `new Coordinate[Count]`.

`ExpandEnvelope(env)` is a bunch of calls to `env.ExpandToInclude(GetX(i), GetY(i))`.

## `ICoordinateSequenceFactory`
Again, leaving out `Ordinate` / `Ordinates` and friends.

`ICoordinateSequence Create(int size, int dimension, int measures)` is all that implementations should need to care about implementing.

"Create it as a copy of this other thing" can have a **major** impact on performance for pretty much every implementation (there's almost *always* a better way to copy from an instance of the same type), **however**, I think we can satisfy that need almost as well with a new "default interface method"*:
```csharp
public interface ICoordinateSequence
{
    /* ... */

    void CopyFrom(ICoordinateSequence other, int offset, int count, IEnumerable<Ordinate> ordinatesToCopy)
    {
        // not writing parameter validation here
        var ordinatesToCopyArray = ordinatesToCopy.ToArray();
        for (int i = 0; i < count; i++)
        {
            foreach (var ordinate in ordinatesToCopyArray)
            {
                this.SetOrdinate(i, ordinate, other.GetOrdinate(i + offset, ordinate));
            }
        }
    }
}
```

*I know that we can't do default interface methods properly, but there's a way to cheat at it that's **almost** as good... instead of a true "default interface method", we can use an extension method with a helper interface... to give an idea, an interface with a "default method" that we wish we could write like this:
```csharp
public interface ISampleInterface
{
    void DoTheThing() => Console.WriteLine("I am doing the thing, but not very well");
}
```
could be delivered like this:
```csharp
public interface ISampleInterface
{
    // DoTheThing is *NOT* here.
}

public interface IDoTheThingBetter
{
    void DoTheThing();
}

public static class SampleInterfaceExtensions
{
    public static void DoTheThing(this ISampleInterface @this)
    {
        if (@this is IDoTheThingBetter thingDoer)
        {
            // "overridden" implementation
            thingDoer.DoTheThing();
            return;
        }

        // default implementation
        Console.WriteLine("I am doing the thing, but not very well");
    }
}
```

## `ICurve`

`IsClosed` is the same as checking whether `StartPoint` and `EndPoint` are equal.

`IsRing` is apparently `IsClosed && IsSimple`, according to its single implementation that isn't called by anyone I can discover right now.

### Strict redundancies
1. `SRID` is `Factory.SRID`.
1. `GeometryType` looks like `GetType().Name`???
1. `Envelope` is `Factory.ToGeometry(EnvelopeInternal)`.
1. `Normalized()` is `Copy().Normalize()` + return the normalized copy.
1. `EqualsExact(g)` is `EqualsExact(g, 0)`.
1. `EqualsNormalized(g)` is `Normalized().EqualsExact(g.Normalized())`.
1. `PointOnSurface` is `InteriorPoint`.
1. `x.Within(y)` is `y.Contains(x)`.
1. `x.CoveredBy(y)` is `y.Covers(x)`.
1. `x.Disjoint(y)` is `!x.Intersects(y)`.
1. `Relate(g, somePattern)` is `Relate(g).Matches(somePattern)`.
1. `Buffer(double, IBufferParameters)` is the only `Buffer` method we need.
    - though I'd kinda like `IBufferParameters` **not** to be an interface...

### Can be implemented via a call to `Apply(...)`
1. `int NumGeometries`
1. `int NumPoints`
1. `Coordinate Coordinate`
1. `Coordinate[] Coordinates`
1. `double[] GetOrdinates(Ordinate)`
1. `Dimension Dimension` (but `OgcGeometryType` will often be enough)
1. `IGeometry Envelope`
1. `Envelope EnvelopeInternal`
1. `bool IsEmpty`

### Can be implemented via `Relate(g)`, though there's often a decent way to short-circuit.
1. `Contains` / `Within`
1. `Covers` / `CoveredBy`
1. `Intersects` / `Disjoint`
1. `Touches`
1. `Crosses`
1. `Overlaps`
1. `EqualsTopologically`

## `IGeometryCollection`
1. `int Count` is `NumGeometries`
1. `this[int]` is `GetGeometryN`

`IGeometry[] Geometries` also could be `this.ToArray()` if we're OK with no longer **defining** it as a view of the underlying data... not exactly a discussion for here though.

## `IGeometryFactory`
These methods are variants of other methods invoke those other methods with some sort of "empty":
1. `CreatePoint()`
1. `CreateLineString()`
1. `CreateLinearRing()`
1. `CreatePolygon()`
1. `CreatePolygon(ILinearRing)`
1. `CreateMultiPoint()`
1. `CreateMultiLineString()`
1. `CreateMultiPolygon()`
1. `CreateGeometryCollection()`

These methods are variants of other `ICoordinateSequence` methods via `CoordinateSequenceFactory`:
1. `CreatePoint(Coordinate)`
1. `CreateLineString(Coordinate[])`
1. `CreateLinearRing(Coordinate[])`
1. `CreatePolygon(Coordinate[])`
1. `CreateMultiPointFromCoords(Coordinate[])`

Finally, `CreatePolygon(ICoordinateSequence)` is `CreatePolygon(CreateLineString(seq))`

## `ILineString`
1. `GetCoordinateN(i)` is `CoordinateSequence.GetCoordinate(i)`
1. `GetPointN(i)` is `Factory.CreatePoint(GetCoordinateN(i))`

## `IMultiCurve`
`bool IsClosed` is `!IsEmpty && Cast<ICurve>().All(g => g.IsClosed)`

## `IPoint`
`X` is `CoordinateSequence.GetX(0)`.  Same for Y, Z, M.

## `IPolygon`
Same idea as in `IGeometryCollection`, we only need either the array or the Num + 

1. `ExteriorRing` is `Shell`.
1. `ILineString[] InteriorRings` is `Holes.ToArray<ILineString>()`
1. `int NumInteriorRings` / `GetInteriorRingN(int)` come from `Holes`, or vice-versa if we don't want to keep defining `Holes` as a view of the underlying data.

## `IPrecisionModel`
`bool IsFloating`, `int MaximumSignificantDigits`, and `void MakePrecise(Coordinate)` are all defined to be the same as their NTS implementations.

## `IGeometryServices`
`CreatePrecisionModel(IPrecisionModel)` is one of the two other overloads depending on the type.

All `CreateGeometryFactory` overloads are equivalent to `CreateGeometryFactory(IPrecisionModel, int, ICoordinateSequenceFactory)`, filling in the defaults from properties where missing.

**Comment by FObermaier** [comment]
Side note: I personally like the `Ordinate` and `Ordiantes` enums more than `HasZ` and `HasM`.

| Interface | Annotation |
|:----------|:---------|
| `ICoordinateBuffer` | Is [used here](https://github.com/NetTopologySuite/NetTopologySuite.IO.SqlServer2008/blob/master/NetTopologySuite.IO.SqlServer2008/Geometries/CoordinateBuffer.cs). Used to be in a `NetTopologySuite.IO` library for reuse in Shapefile IO, but never made it that far. |
| `ICoordinateSequence` | The comment to  `ToCoordinateArray()` is partially wrong. For `CoordinateArraySequence` the internal array is returned without copying anything |

Additionally, please see https://github.com/NetTopologySuite/GeoAPI/issues/68#issuecomment-472326934

**Comment by airbreather** [comment]
We did #68 instead.
