### ISSUE TITLE
support .NET core 3.0

### ISSUE THREAD

**Issue by yjacques940** [NetTopologySuite/GeoAPI#71]
We recently upgraded to dotnet core 3.0. We need GeoAPI in our api. We actually need this feature as fast as possible, to deploy in production. 

What's needed : 
- Make the GeoAPI compatible with .net core 3.0

Please answer me when i'ts done.
Thanks

**Comment by airbreather** [comment]
GeoAPI is compatible with .NET Core 3.0.

Entity Framework Core 3.0 uses NetTopologySuite 2.x, which no longer uses GeoAPI.  ProjNet4GeoAPI 2.x no longer uses GeoAPI either (so we now use the ProjNet package on NuGet).

We have no plans to continue updating GeoAPI to 2.x or above.  The interesting parts of GeoAPI moved to NetTopologySuite / ProjNet4GeoAPI, and the rest went away.

**Comment by yjacques940** [comment]
Good, Thank you!
