### ISSUE TITLE
GeoAPI 3.0 OGC standard

### ISSUE THREAD

**Issue by petrpokorny** [NetTopologySuite/GeoAPI#9]
Hey there - I am wondering if there is any plan to update GeoAPI.NET to GeoAPI 3.0 standard so that it will contain (for example) Feature-related interfaces and so on.(https://github.com/opengeospatial/geoapi/tree/master/geoapi/src/main/java/org/opengis/feature)

Thanks, Petr

**Comment by DGuidi** [comment]
actually interfaces are defined in [NTS](https://github.com/NetTopologySuite/NetTopologySuite/tree/master/NetTopologySuite/Features), there's a plan (at least an idea) to move definitions to GeoAPI, maybe in a next iteration.
Features code it's very important and related to [SharpMap](http://sharpmap.codeplex.com/) too.
